[package]
name = "file-base64"
version = "0.1.0"
authors = ["Sajjad <Sajjad.taqinezhad@Gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12.0"
